import ControlRoomShell from "@/components/control-room/ControlRoomShell";
import HistoryStorageNotice from "@/components/control-room/HistoryStorageNotice";
import { getAnalyticsStorage } from "@/lib/control-room/analytics/storage";
import { getControlRoomSnapshot } from "@/lib/control-room/get-control-room-snapshot";

export default async function AnalyticsPage({ searchParams }: { searchParams: Promise<{ state?: string }> }) {
  const { state } = await searchParams;
  const snapshot = getControlRoomSnapshot();
  const storage = await getAnalyticsStorage();
  const [snapshots, attribution] = storage.status === "ready" ? await Promise.all([storage.repository.list(12), storage.repository.leadAttribution()]) : [null, null];
  return <ControlRoomShell activeSection="analytics" eyebrow="TBD Control Room · Analytics" title="Aggregate analytics and conversion evidence" description="Privacy-minimised evidence from Cloudflare Web Analytics and the private lead workflow. No cookie, visitor identifier, IP address, browser or device profile is added." baselineReviewDate={snapshot.baselineReviewDate} lastUpdatedDate={snapshot.lastUpdatedDate}>
    {state ? <p className="rounded-xl border border-black/8 bg-white p-4 text-sm">Capture result: <strong>{state.replaceAll("-", " ")}</strong>.</p> : null}
    {storage.status !== "ready" ? <HistoryStorageNotice reason={storage.reason} /> : <>
      <section className="rounded-[1.35rem] border border-black/8 bg-white p-5 sm:p-7"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-gray-500">Cloudflare Web Analytics · aggregate only</p><h2 className="mt-2 text-2xl font-bold">Record a reviewed RUM snapshot</h2><p className="mt-2 text-sm text-gray-600">Enter only aggregate values visible in the authorised Cloudflare dashboard. Leave a Core Web Vital blank when Cloudflare has insufficient data.</p><form action="/control-room/analytics/capture" method="post" className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><label className="text-sm font-semibold">Period start<input required type="date" name="periodStart" className="mt-1 min-h-11 w-full rounded-lg border border-black/15 px-3" /></label><label className="text-sm font-semibold">Period end<input required type="date" name="periodEnd" className="mt-1 min-h-11 w-full rounded-lg border border-black/15 px-3" /></label><label className="text-sm font-semibold">Page views<input required type="number" min="0" name="pageViews" className="mt-1 min-h-11 w-full rounded-lg border border-black/15 px-3" /></label><label className="text-sm font-semibold">Visits<input required type="number" min="0" name="visits" className="mt-1 min-h-11 w-full rounded-lg border border-black/15 px-3" /></label><label className="text-sm font-semibold">LCP p75 · ms<input type="number" min="0" name="lcpP75Ms" className="mt-1 min-h-11 w-full rounded-lg border border-black/15 px-3" /></label><label className="text-sm font-semibold">INP p75 · ms<input type="number" min="0" name="inpP75Ms" className="mt-1 min-h-11 w-full rounded-lg border border-black/15 px-3" /></label><label className="text-sm font-semibold">CLS p75 · ×1000<input type="number" min="0" name="clsP75Milli" className="mt-1 min-h-11 w-full rounded-lg border border-black/15 px-3" /></label><label className="text-sm font-semibold">Review note<input name="notes" maxLength={500} className="mt-1 min-h-11 w-full rounded-lg border border-black/15 px-3" /></label><div className="sm:col-span-2 xl:col-span-4"><button className="min-h-11 rounded-lg bg-black px-5 text-sm font-semibold text-white">Save aggregate snapshot</button></div></form></section>
      <section className="rounded-[1.35rem] border border-black/8 bg-white p-5 sm:p-7"><h2 className="text-2xl font-bold">Stored RUM snapshots</h2>{snapshots?.length ? <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[48rem] text-left text-sm"><thead><tr className="border-b border-black/10"><th className="py-2">Period</th><th>Views</th><th>Visits</th><th>LCP p75</th><th>INP p75</th><th>CLS p75</th></tr></thead><tbody>{snapshots.map((item) => <tr key={item.id} className="border-b border-black/6"><td className="py-3">{item.periodStart} to {item.periodEnd}</td><td>{item.pageViews}</td><td>{item.visits}</td><td>{item.lcpP75Ms ?? "Unavailable"}</td><td>{item.inpP75Ms ?? "Unavailable"}</td><td>{item.clsP75Milli === null ? "Unavailable" : item.clsP75Milli / 1000}</td></tr>)}</tbody></table></div> : <p className="mt-3 text-sm text-gray-600">No reviewed snapshot has been stored yet.</p>}</section>
      <section className="rounded-[1.35rem] border border-black/8 bg-white p-5 sm:p-7"><h2 className="text-2xl font-bold">Enquiry attribution and outcomes</h2><p className="mt-2 text-sm text-gray-600">Internal referring page is captured only when a visitor moves directly to Contact from another page on this site. No cross-session or cross-site identifier is used.</p><div className="mt-5 grid gap-6 xl:grid-cols-2"><div><h3 className="font-bold">Originating pages</h3>{attribution?.sources.length ? <ul className="mt-3 divide-y divide-black/8">{attribution.sources.map((row) => <li key={`${row.sourcePath}-${row.status}`} className="flex justify-between gap-4 py-2 text-sm"><span>{row.sourcePath} · {row.status}</span><strong>{row.total}</strong></li>)}</ul> : <p className="mt-3 text-sm text-gray-500">No enquiry evidence yet.</p>}</div><div><h3 className="font-bold">Services and outcomes</h3>{attribution?.services.length ? <ul className="mt-3 divide-y divide-black/8">{attribution.services.map((row) => <li key={`${row.service}-${row.status}`} className="flex justify-between gap-4 py-2 text-sm"><span>{row.service} · {row.status}</span><strong>{row.total}</strong></li>)}</ul> : <p className="mt-3 text-sm text-gray-500">No selected-service evidence yet.</p>}</div></div></section>
    </>}
  </ControlRoomShell>;
}
