import type { AiAnalysisRecord } from "@/lib/control-room/analyst/domain";

export default function AiAnalysisPanel({ records, period, pages, state }: { records: readonly AiAnalysisRecord[]; period: "28d" | "90d"; pages: "included" | "excluded"; state?: string }) {
  return <section className="rounded-[1.35rem] border border-black/8 bg-white p-5 sm:p-7" aria-labelledby="ai-analyst-title">
    <p className="text-xs font-semibold uppercase tracking-[0.16em] text-gray-500">Human-approved AI analyst</p>
    <h2 id="ai-analyst-title" className="mt-2 text-2xl font-bold">Generate a private evidence draft</h2>
    <p className="mt-3 max-w-4xl text-sm leading-relaxed text-gray-600">The model receives the same bounded brief shown below. Exact Search queries, lead details, credentials and identity are excluded. Generation is deliberately manual and usage-billed by Cloudflare. A result is saved as a draft; it cannot publish content, deploy code or create an action.</p>
    {state ? <p className="mt-4 rounded-xl bg-[#f7f7f4] p-4 text-sm">Analyst result: <strong>{state.replaceAll("-", " ")}</strong>.</p> : null}
    <form action="/control-room/analysis-brief/generate" method="post" className="mt-5">
      <input type="hidden" name="period" value={period} /><input type="hidden" name="pages" value={pages} />
      <button className="min-h-11 rounded-lg bg-black px-5 text-sm font-semibold text-white">Generate reviewed-data draft</button>
    </form>
    <div className="mt-7 space-y-5">
      {records.length ? records.map((record) => <article key={record.id} className="rounded-2xl border border-black/8 bg-[#f7f7f4] p-5">
        <div className="flex flex-wrap items-center justify-between gap-3"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-gray-500">{record.periodId} · {record.model}</p><span className="rounded-full border border-black/12 px-3 py-1 text-xs font-semibold uppercase">{record.status}</span></div>
        <h3 className="mt-4 text-xl font-bold">Draft summary</h3><p className="mt-2 text-sm leading-relaxed text-gray-700">{record.draft.summary}</p>
        <div className="mt-5 grid gap-5 xl:grid-cols-2"><div><h4 className="font-bold">Findings</h4>{record.draft.findings.length ? <ul className="mt-3 space-y-3">{record.draft.findings.map((finding, index) => <li key={`${record.id}-finding-${index}`} className="rounded-xl bg-white p-4 text-sm"><strong>{finding.title}</strong><p className="mt-1 leading-relaxed text-gray-600">{finding.observation}</p><p className="mt-2 text-xs text-gray-500">Confidence {finding.confidence} · Evidence {finding.evidenceIds.join(", ") || "none"} · Limitation: {finding.limitation}</p></li>)}</ul> : <p className="mt-2 text-sm text-gray-500">No supported finding returned.</p>}</div><div><h4 className="font-bold">Recommended actions for review</h4>{record.draft.recommendations.length ? <ul className="mt-3 space-y-3">{record.draft.recommendations.map((recommendation, index) => <li key={`${record.id}-recommendation-${index}`} className="rounded-xl bg-white p-4 text-sm"><strong>{recommendation.title}</strong><p className="mt-1 leading-relaxed text-gray-600">{recommendation.rationale}</p><p className="mt-2 text-xs text-gray-500">Priority {recommendation.priority} · Success measure: {recommendation.successMeasure} · Evidence {recommendation.evidenceIds.join(", ") || "none"}</p></li>)}</ul> : <p className="mt-2 text-sm text-gray-500">No supported recommendation returned.</p>}</div></div>
        <p className="mt-5 text-sm text-gray-600"><strong>Overall limitation:</strong> {record.draft.overallLimitation}</p><p className="mt-2 break-all font-mono text-[0.68rem] text-gray-500">Source packet {record.sourcePacketHash} · created {record.createdAt}{record.reviewedAt ? ` · reviewed ${record.reviewedAt}` : ""}</p>
        {record.status === "draft" ? <div className="mt-5 flex flex-wrap gap-3"><form action="/control-room/analysis-brief/review" method="post"><input type="hidden" name="id" value={record.id} /><input type="hidden" name="status" value="approved" /><button className="min-h-11 rounded-lg bg-black px-4 text-sm font-semibold text-white">Approve draft</button></form><form action="/control-room/analysis-brief/review" method="post"><input type="hidden" name="id" value={record.id} /><input type="hidden" name="status" value="rejected" /><button className="min-h-11 rounded-lg border border-black/15 bg-white px-4 text-sm font-semibold">Reject draft</button></form></div> : null}
      </article>) : <p className="rounded-xl bg-[#f7f7f4] p-4 text-sm text-gray-600">No AI draft has been generated. The deterministic Analysis Brief remains available below.</p>}
    </div>
  </section>;
}
