import Link from "next/link";
import type { WebmasterAnalysisBriefV1 } from "@/lib/control-room/analysis-brief/domain";
const metric = (value: number | null | undefined) => value == null ? "Not available" : new Intl.NumberFormat("en-GB", { maximumFractionDigits: 3 }).format(value);
export default function AnalysisBriefEvidenceSections({ brief }: { brief: WebmasterAnalysisBriefV1 }) { return <>
  <section className="mt-6 rounded-[1.35rem] border border-black/8 bg-white p-5 sm:p-7"><h2 className="text-xl font-bold">Page-level Search evidence</h2>{!brief.pageLevelEvidenceIncluded ? <p className="mt-3 text-sm text-gray-600">Page-level Search evidence was excluded from this brief.</p> : !brief.pagePerformance.rows.length ? <p className="mt-3 text-sm text-gray-600">No page-level evidence is available.</p> : <div className="mt-4 overflow-x-auto"><table className="min-w-[760px] text-left text-sm"><caption className="sr-only">Bounded current and previous page-level Search evidence</caption><thead><tr className="border-b"><th scope="col" className="p-2">Page</th><th scope="col" className="p-2">Current clicks</th><th scope="col" className="p-2">Previous clicks</th><th scope="col" className="p-2">Current impressions</th><th scope="col" className="p-2">Previous impressions</th><th scope="col" className="p-2">Classification</th></tr></thead><tbody>{brief.pagePerformance.rows.map((row) => <tr key={row.path} className="border-b"><td className="max-w-72 break-all p-2">{row.path}</td><td className="p-2">{metric(row.current?.clicks)}</td><td className="p-2">{metric(row.previous?.clicks)}</td><td className="p-2">{metric(row.current?.impressions)}</td><td className="p-2">{metric(row.previous?.impressions)}</td><td className="p-2">{row.classification.replaceAll("_", " ")}</td></tr>)}</tbody></table></div>}</section>
  <section className="mt-6 rounded-[1.35rem] border border-black/8 bg-white p-5 sm:p-7"><h2 className="text-xl font-bold">Device evidence</h2>{!brief.devicePerformance.rows.length ? <p className="mt-3 text-sm text-gray-600">No device-level evidence is available.</p> : <ul className="mt-3 grid gap-3 sm:grid-cols-3">{brief.devicePerformance.rows.map((row) => <li key={row.device} className="rounded-lg bg-[#f7f7f4] p-3 text-sm"><strong>{row.device}</strong><br />Current clicks: {metric(row.current?.clicks)}<br />Previous clicks: {metric(row.previous?.clicks)}<br />Current impressions: {metric(row.current?.impressions)}<br />Previous impressions: {metric(row.previous?.impressions)}</li>)}</ul>}</section>
  <section className="mt-6 rounded-[1.35rem] border border-black/8 bg-white p-5 sm:p-7"><h2 className="text-xl font-bold">Recorded website changes</h2>{!brief.recordedChanges.length ? <p className="mt-3 text-sm text-gray-600">No recorded website changes were found for this evidence period.</p> : <ul className="mt-3 space-y-3">{brief.recordedChanges.map((item) => <li key={item.id} className="rounded-lg bg-[#f7f7f4] p-3 text-sm"><strong>{item.title}</strong> · {item.type} · {item.verificationState}<br />{item.summary}<br />{item.affectedPath ?? "No affected path"}</li>)}</ul>}</section>
  <section className="mt-6 rounded-[1.35rem] border border-black/8 bg-white p-5 sm:p-7"><h2 className="text-xl font-bold">Existing action evidence</h2>{!brief.actionEvidence.length ? <p className="mt-3 text-sm text-gray-600">No action outcome evidence is currently available.</p> : <ul className="mt-3 space-y-3">{brief.actionEvidence.map((item) => <li key={item.id} className="rounded-lg bg-[#f7f7f4] p-3 text-sm"><strong>{item.actionId}</strong> · {item.evaluationStatus} · {item.verificationState}<br />Expected: {item.expectedOutcome}<br />Observed: {item.observedOutcome}</li>)}</ul>}</section>
  <section className="mt-6 rounded-[1.35rem] border border-black/8 bg-white p-5 sm:p-7"><h2 className="text-xl font-bold">Evidence index</h2><ul className="mt-3 space-y-2">{brief.evidenceReferences.map((reference) => <li key={reference.label}><Link className="text-sm font-semibold underline" href={reference.href}>{reference.label} · {reference.type} · {reference.sensitivity}</Link></li>)}</ul></section>
</>; }
