import Link from "next/link";
import AnalysisBriefActions from "@/components/control-room/AnalysisBriefActions";
import AnalysisBriefEvidenceSections from "@/components/control-room/AnalysisBriefEvidenceSections";
import ControlRoomShell from "@/components/control-room/ControlRoomShell";
import HistoryStorageNotice from "@/components/control-room/HistoryStorageNotice";
import { buildWebmasterAnalysisBrief } from "@/lib/control-room/analysis-brief/build-brief";
import { createAnalysisBriefCopyPayloads } from "@/lib/control-room/analysis-brief/copy-payloads";
import { getHistoryStorage } from "@/lib/control-room/history/storage";

export default async function AnalysisBriefPage({ searchParams }: { searchParams: Promise<{ period?: string; pages?: string }> }) {
  const query = await searchParams; const period = query.period === "90d" ? "90d" : "28d"; const pages = query.pages === "excluded" ? "excluded" : "included"; const storage = await getHistoryStorage();
  if (storage.status !== "ready") return <ControlRoomShell activeSection="analysis-brief" eyebrow="TBD Control Room · Analysis brief" title="Webmaster Analysis Brief" description="Copy-ready technical and search evidence for manual analysis." baselineReviewDate="22 July 2026" lastUpdatedDate="22 July 2026"><HistoryStorageNotice reason={storage.reason} /></ControlRoomShell>;
  const packet = await storage.repository.buildEvidencePacket(period, new Date().toISOString()); const brief = await buildWebmasterAnalysisBrief(packet, { pageLevelEvidenceIncluded: pages === "included", generatedAt: new Date().toISOString() }); const { markdown, json, chatgpt } = createAnalysisBriefCopyPayloads(brief);
  return <ControlRoomShell activeSection="analysis-brief" eyebrow="TBD Control Room · Analysis brief" title="Webmaster Analysis Brief" description="Copy-ready technical and search evidence for manual analysis." baselineReviewDate="22 July 2026" lastUpdatedDate="22 July 2026">
    <section className="analysis-brief-notice rounded-[1.35rem] border border-black/8 bg-[#f7f7f4] p-5 sm:p-7"><h2 className="text-xl font-bold">Private, deterministic source evidence</h2><p className="mt-3 text-sm leading-relaxed">No AI service is contacted. Exact Search queries, credentials and authentication identity are excluded. Copying and printing do not alter stored data or create a file.</p></section>
    <section className="analysis-brief-controls mt-6 rounded-[1.35rem] border border-black/8 bg-white p-5"><h2 className="text-xl font-bold">Report options</h2><div className="mt-3 flex flex-wrap gap-3">{(["28d", "90d"] as const).map((value) => <Link key={value} href={`/control-room/analysis-brief?period=${value}&pages=${pages}`} className={`rounded-lg px-4 py-3 text-sm font-semibold ${period === value ? "bg-black text-white" : "border"}`}>{value}</Link>)}{(["included", "excluded"] as const).map((value) => <Link key={value} href={`/control-room/analysis-brief?period=${period}&pages=${value}`} className={`rounded-lg px-4 py-3 text-sm font-semibold ${pages === value ? "bg-black text-white" : "border"}`}>{value === "included" ? "Include page evidence" : "Exclude page evidence"}</Link>)}</div></section>
    <div className="mt-6"><AnalysisBriefActions chatgpt={chatgpt} markdown={markdown} json={json} /></div>
    <article className="analysis-brief-report mt-6 rounded-[1.35rem] border border-black/8 bg-white p-5 sm:p-7"><h2 className="text-2xl font-bold">Report</h2><p className="mt-3 text-sm">Period: {brief.reportPeriod}. Restricted Search query text: excluded.</p><h3 className="mt-6 text-xl font-bold">Evidence coverage</h3><ul className="mt-3 grid gap-2 text-sm sm:grid-cols-2">{Object.entries(brief.evidenceCoverage).map(([label, state]) => <li key={label} className="rounded-lg bg-[#f7f7f4] p-3"><strong>{label}</strong>: {String(state)}</li>)}</ul><h3 className="mt-6 text-xl font-bold">Technical performance</h3>{brief.technicalPerformance.length ? <ul className="mt-3 space-y-2">{brief.technicalPerformance.map((item) => <li key={item.runId} className="rounded-lg bg-[#f7f7f4] p-3 text-sm">{item.targetId} · {item.strategy} · Performance {item.performanceScore ?? "Not available"} · LCP {item.lcpValue ?? "Not available"} ms · CLS {item.clsValue ?? "Not available"}</li>)}</ul> : <p className="mt-3 text-sm">No PageSpeed snapshot is available.</p>}<p className="mt-3 text-sm">{brief.technicalComparison ? `Comparable deltas: Performance ${brief.technicalComparison.performanceScoreDelta ?? "Not available"}, LCP ${brief.technicalComparison.lcpValueDelta ?? "Not available"} ms, CLS ${brief.technicalComparison.clsValueDelta ?? "Not available"}.` : "No previous comparable PageSpeed snapshot is available."}</p><h3 className="mt-6 text-xl font-bold">Search performance</h3><p className="mt-3 text-sm">Current: {brief.searchPerformance.current ? `${brief.searchPerformance.current.startDate} to ${brief.searchPerformance.current.endDate}` : "Not available"}. Previous: {brief.searchPerformance.previous ? `${brief.searchPerformance.previous.startDate} to ${brief.searchPerformance.previous.endDate}` : "Not available"}.</p><h3 className="mt-6 text-xl font-bold">Data quality and limitations</h3><ul className="mt-3 list-disc space-y-1 pl-5 text-sm">{brief.limitations.map((item) => <li key={item}>{item}</li>)}</ul></article>
    <AnalysisBriefEvidenceSections brief={brief} />
    <details className="mt-6 rounded-[1.35rem] border border-black/8 bg-white p-5"><summary className="cursor-pointer font-semibold">Review ChatGPT copy instruction and brief</summary><pre className="mt-4 whitespace-pre-wrap break-words text-xs">{chatgpt}</pre></details>
    <section className="analysis-brief-workflow mt-6 rounded-[1.35rem] border border-black/8 bg-white p-5"><h2 className="text-xl font-bold">How to use this report</h2><ol className="mt-3 list-decimal space-y-1 pl-5 text-sm"><li>Copy for ChatGPT and paste into the Tan Bui Designs ChatGPT project.</li><li>Review the analysis and select one action.</li><li>Ask for one narrow Codex task, then review implementation and later measure the outcome.</li></ol></section>
  </ControlRoomShell>;
}
