import ControlRoomShell from "@/components/control-room/ControlRoomShell";
import HistoryStorageNotice from "@/components/control-room/HistoryStorageNotice";
import { getHistoryStorage } from "@/lib/control-room/history/storage";

export default async function EvidencePage({ searchParams }: { searchParams: Promise<{ state?: string }> }) {
  const { state } = await searchParams; const storage = await getHistoryStorage(); const disabled = storage.status !== "ready";
  return <ControlRoomShell activeSection="evidence" eyebrow="TBD Control Room · Evidence" title="Change and action evidence" description="Append-only internal records. Corrections supersede earlier entries; they never delete or rewrite them." baselineReviewDate="18 July 2026" lastUpdatedDate="18 July 2026">
    {state ? <p role="status" className="rounded-xl border border-black/8 bg-white p-4 text-sm">Request state: {state.replaceAll("-", " ")}.</p> : null}
    {disabled ? <HistoryStorageNotice reason={storage.reason} /> : null}
    <div className="grid gap-6 xl:grid-cols-2">
      <form method="post" action="/control-room/evidence/change" className="rounded-[1.35rem] border border-black/8 bg-white p-5 sm:p-7"><h2 className="text-2xl font-bold">Record change</h2><input type="hidden" name="id" value={crypto.randomUUID()} />
        <label className="mt-5 block text-sm font-semibold">Date<input required name="occurredAt" type="date" className="mt-2 min-h-11 w-full rounded-lg border px-3" /></label><label className="mt-4 block text-sm font-semibold">Event type<select name="eventType" className="mt-2 min-h-11 w-full rounded-lg border px-3"><option value="technical">Technical</option><option value="deployment">Deployment</option><option value="content">Content</option><option value="seo">SEO</option><option value="design">Design</option><option value="analytics">Analytics</option><option value="security">Security</option><option value="other">Other</option></select></label><label className="mt-4 block text-sm font-semibold">Title<input required maxLength={120} name="title" className="mt-2 min-h-11 w-full rounded-lg border px-3" /></label><label className="mt-4 block text-sm font-semibold">Affected local path (optional)<input maxLength={300} name="affectedPath" placeholder="/work" className="mt-2 min-h-11 w-full rounded-lg border px-3" /></label><label className="mt-4 block text-sm font-semibold">Summary<textarea required maxLength={1500} name="summary" rows={5} className="mt-2 w-full rounded-lg border p-3" /></label><label className="mt-4 block text-sm font-semibold">Lifecycle<select name="lifecycleState" className="mt-2 min-h-11 w-full rounded-lg border px-3"><option value="implemented">Implemented</option><option value="planned">Planned</option><option value="deployed">Deployed</option><option value="reverted">Reverted</option><option value="corrected">Corrected</option></select></label><label className="mt-4 block text-sm font-semibold">Supersedes event UUID (optional)<input maxLength={36} name="supersedesId" className="mt-2 min-h-11 w-full rounded-lg border px-3" /></label><button disabled={disabled} className="mt-5 min-h-11 rounded-lg bg-black px-5 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-40">Record append-only change</button>
      </form>
      <form method="post" action="/control-room/evidence/action" className="rounded-[1.35rem] border border-black/8 bg-white p-5 sm:p-7"><h2 className="text-2xl font-bold">Record action evidence</h2><input type="hidden" name="id" value={crypto.randomUUID()} />
        <label className="mt-5 block text-sm font-semibold">Action ID<input required maxLength={120} name="actionId" className="mt-2 min-h-11 w-full rounded-lg border px-3" /></label><label className="mt-4 block text-sm font-semibold">Metric family<select name="metricFamily" className="mt-2 min-h-11 w-full rounded-lg border px-3"><option value="manual">Manual</option><option value="pagespeed">PageSpeed</option><option value="search">Search</option><option value="mixed">Mixed</option></select></label><label className="mt-4 block text-sm font-semibold">Expected outcome<textarea required maxLength={1500} name="expectedOutcome" rows={4} className="mt-2 w-full rounded-lg border p-3" /></label><label className="mt-4 block text-sm font-semibold">Observed outcome<textarea required maxLength={1500} name="observedOutcome" rows={4} className="mt-2 w-full rounded-lg border p-3" /></label><label className="mt-4 block text-sm font-semibold">Evaluation<select name="evaluationStatus" className="mt-2 min-h-11 w-full rounded-lg border px-3"><option value="pending">Pending</option><option value="positive">Positive</option><option value="negative">Negative</option><option value="mixed">Mixed</option><option value="inconclusive">Inconclusive</option></select></label><label className="mt-4 block text-sm font-semibold">Supersedes evidence UUID (optional)<input maxLength={36} name="supersedesId" className="mt-2 min-h-11 w-full rounded-lg border px-3" /></label><button disabled={disabled} className="mt-5 min-h-11 rounded-lg bg-black px-5 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-40">Record append-only evidence</button>
      </form>
    </div>
  </ControlRoomShell>;
}
