// This file is generated by scripts/generate-homepage-logo-manifest.mjs.
// Add WebP files to public/homepage and rerun the generator.

export type HomepageLogo = {
  readonly id: string;
  readonly src: string;
  readonly alt: string;
};

export const homepageLogos = [
  {
    "id": "adelie",
    "src": "/homepage/Adelie.webp",
    "alt": "Adelie logo"
  },
  {
    "id": "british-airways",
    "src": "/homepage/British Airways.webp",
    "alt": "British Airways logo"
  },
  {
    "id": "compass",
    "src": "/homepage/Compass.webp",
    "alt": "Compass logo"
  },
  {
    "id": "coop",
    "src": "/homepage/Coop.webp",
    "alt": "Coop logo"
  },
  {
    "id": "costa",
    "src": "/homepage/Costa.webp",
    "alt": "Costa logo"
  },
  {
    "id": "cox-automotive",
    "src": "/homepage/Cox Automotive.webp",
    "alt": "Cox Automotive logo"
  },
  {
    "id": "easyjet",
    "src": "/homepage/easyJet.webp",
    "alt": "easyJet logo"
  },
  {
    "id": "eat",
    "src": "/homepage/EAT.webp",
    "alt": "EAT logo"
  },
  {
    "id": "enjays",
    "src": "/homepage/Enjays.webp",
    "alt": "Enjays logo"
  },
  {
    "id": "foodbuy",
    "src": "/homepage/foodbuy.webp",
    "alt": "foodbuy logo"
  },
  {
    "id": "greencore",
    "src": "/homepage/Greencore.webp",
    "alt": "Greencore logo"
  },
  {
    "id": "londis",
    "src": "/homepage/Londis.webp",
    "alt": "Londis logo"
  },
  {
    "id": "nhs",
    "src": "/homepage/NHS.webp",
    "alt": "NHS logo"
  },
  {
    "id": "on-a-roll",
    "src": "/homepage/On A Roll.webp",
    "alt": "On A Roll logo"
  },
  {
    "id": "poundland",
    "src": "/homepage/Poundland.webp",
    "alt": "Poundland logo"
  },
  {
    "id": "tesco",
    "src": "/homepage/tesco.webp",
    "alt": "tesco logo"
  },
  {
    "id": "urban-eat",
    "src": "/homepage/Urban Eat.webp",
    "alt": "Urban Eat logo"
  }
] as const satisfies readonly HomepageLogo[];
