// This file is generated by scripts/generate-playground-manifest.mjs.
// Add WebP files to public/playground and rerun the manifest generator.

export type PlaygroundLayout = "wide" | "tall" | "square" | "standard" | "panorama" | "portrait";
export type PlaygroundCorner = "soft" | "swept" | "opposite" | "round";

export type PlaygroundItem = {
  readonly id: string;
  readonly kind: "image" | "placeholder";
  readonly src?: string;
  readonly category: string;
  readonly title: string;
  readonly alt: string;
  readonly layout: PlaygroundLayout;
  readonly corner: PlaygroundCorner;
  readonly art: number;
};

export const playgroundItems = [] as const satisfies readonly PlaygroundItem[];
